spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
aws:
  region: ${AWS_REGION}
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_ACCESS_KEY}
  s3-bucket-name: ${AWS_S3_BUCKET_NAME}
cronica:
  ca:
    endpoint: ${CRONICA_CA_ENDPOINT}
blockchain:
  wallet-private-key: ${WALLET_PRIVATE_KEY}
  quorum-node-endpoint: ${QUORUM_ENDPOINT}
issuer:
  bank-code: ${ISSUER_BANK_CODE}