package io.cronica.api.pdfgenerator.component.metrics;

public enum MethodID {

    SIGN_DOCUMENT_SUCCESSFUL_REQUESTS,
    SIGN_DOCUMENT_FAILED_REQUESTS,
    SIGN_DOCUMENT_REQUEST_TIME,
    COUNT_OF_SUCCESSFUL_DOCUMENT_GENERATIONS,
    COUNT_OF_FAILED_DOCUMENT_GENERATIONS,
    TIME_OF_DOCUMENT_GENERATION
}
